name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Starter Code
        uses: actions/checkout@v2
      - name: Checkout to solution repo
        uses: actions/checkout@v2
        with: 
          repository: se-buw/fm4se-featuremodels-solution
          path: fm4se-featuremodels-solution
          token: ${{ secrets.SOLUTION_REPO_TOKEN }}

      - name: Copy test files
        run: cp -r fm4se-featuremodels-solution/src/test/* ${{ github.workspace }}/src/test/
      
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Display Java version
        run: java -version
      
      - uses: education/autograding@v1
